### ISSUE TITLE
How to pass an existing argument to a script?

### ISSUE THREAD

**Issue by Gys** [TekWizely/run#3]
Hi!

I want to run `react-native run-ios`
And sometimes `react-native run-ios --device` or `react-native run-ios --device MyPhone`

So I defined this Runfile:

    ios:
      react-native run-ios ${1} ${2}

But then I get an error when I type: `run ios --device`
Error: `flag provided but not defined: -device`

A workaround might be to define possible arguments as commandline options in `run`. But that seems a little cumbersome.
Or I could define a different command for each possible parameter (and combination). Also not ideal I think.

Related question: is `${*}` also supported, to pass all arguments as one?

**Comment by TekWizely** [comment]
Greetings @Gys !

So at the moment, the following should work:

```
run ios -- --device
```
The flag parser stops at `--` and considers everything after as args.

Additionally, I have been grinding on the issue and have 2 features I'm thinking of adding:

##### Pass-through ALL args when no options defined

If the command does not specify any options, then just pass through the entire argument list without looking for flags.

This would mean that `run command -h|--help` would not be supported, but that's not terrible, since `run help command` does the same thing.

It may be better to support a command config argument to enable this behavior, something like `.NOHELP = true`

So then 1) no configured options plus 2) `.NOHELP = true` => Pass through all arguments

NOTE: With this solution, Run cannot auto-generate useful help for the options, but you could add your option section in the command description.

##### Specify pass-through arguments

Another option I'm considering is a slight modification to the OPTION definition to indicate that you want the argument passed through.

So the standard option format is like:
```
OPTION VARNAME   -s, --long <name> Description
```

Thinking that we could omit the `VARNAME` section to indicate that we want the argument passed through. i.e.

```
OPTION    -s, --long <name> Description
```

This would still auto-generate the option help text, but instead of creating an environment variable from the option, it would pass the option+value as arguments of the script.

One challenge her is the formatting of the option passed into the script.

Run accepts several formats for arguments, and since I (currently) use Go's flag package to parse them, I don't think I'm privy to the exact pattern used when the argument is parsed.

We could settle on a standard, which might be:
* If both short and log args are specified, used short arg for pass-through.
* String args are passed through as `-a=value`
* Boolean args that resolve to true are passed through as `-b`
* Boolean args that resolve to false are passed through as `-b=0`

That could work.

the first option likely makes the most sense.

Thank you for taking the time to open an issue, and please let me know your thoughts on this.

**Comment by Gys** [comment]
Hi @TekWizely 

Happy to see you are putting serious thoughts in this!

I think the 'Pass-through ALL args when no options defined' option is the best one. 
Regarding the .NOHELP idea: you could also just drop the -h / --help option. Because there is already a 'help <command>' option. Just simplify! Having no -h option is also more consistent met the 'list' parameter, because there is no -l / --list either. 

The current '--' option is not documented? You should add it.

And how about my final question: is ${*} also supported, to pass all arguments as one?

Talking about consistency: 

    ## Hello world example.
    hello:
      echo "Hello, world"

Is the same as:

    ## 
    # Hello world example.
    hello:
      echo "Hello, world"

Maybe just drop the  support for `## Hello world example.`

**Comment by TekWizely** [comment]
OK I have  a WIP PR for this which passes all args through to the command script if no explicit options are defined in the commend header.

I'll consider dropping `-h|--help` auto-support but I aded it because its how I like to get help on tools with sub-commands, so I found myself typing it alot :)

re `${*}` - There's no special support for it - Can you explain what use case your 'etrying to achieve with it and what a Runfile might look like?

re: Single-line descriptions : I added this feature because it keeps things terse and matches a pattern Ive seen people use in makefiles for adding lightweight documentation (with a help task to print the target+descriptions).  It gives the user an easy way to make incremental steps in documentation while keeping their Runfile tight and small.

Run actually supports formats that go from mild to wild ... Try this:

```
####################
# Hello world example
####################
## Prints Hello, World
# Prints Hello, Newman
###################
hello:
	echo "Hello, Newman"
```

**Comment by Gys** [comment]
Forget the `${*)`. I was mixing it up with parameters pass-through. 

After dropping `-h|--help` the help auto-support will still be available with `help <command>`? Dropping `-h|--help` would be more consistent with the list-command (`run list` and `run help` plus maybe later `run version`) plus not interfere with the parameter pass-throught.
Another idea: to type less (good point :-) you could use the `?` char for the same functionallity to `help`: `run ?` and `run ? <command>`

**Comment by TekWizely** [comment]
OK I have updated the documentation and think the PR (#5) is ready to merge.

@Gys care to make a pass over the changes and let me know your thoughts?

**Comment by Gys** [comment]
Perefect solution!

**Comment by TekWizely** [comment]
@Gys OK the PR is merged

hank you for participating in my project and please let me know if you run into any issues.

-TW

**Comment by TekWizely** [comment]
@all-contributors please add @Gys  for bug
