### ISSUE TITLE
Consider adding a .RUNFILEDIR attribute

### ISSUE THREAD

**Issue by rburchell** [TekWizely/run#52]
With the use of `run` when not in a directory next to the Runfile, it would be nice to have a convenient way to make paths relative to the primary Runfile.

It's possible to do this already, but it's awkward in that it requires shell code, and it needs to be duplicated into each step that requires it, e.g:

```
deploy-reviewer:
    RUNFILEDIR=$(dirname "${RUNFILE}")
    cd "${RUNFILEDIR}/foo"
    # ... actually do useful things
```

If, instead, we could do this, IMHO it becomes quite a bit nicer with many different commands:

```
EXPORT RUNFILEDIR := ${.RUNFILEDIR}

deploy-reviewer:
    cd "${RUNFILEDIR}/foo"
    # ... actually do useful things
```

On the subject of attributes, with includes being a thing now, it might also be convenient to have attributes for the paths relevant for the imported Runfile, to be able to more easily make reusable things. The included Runfile may be in many directories all over the place, and want to make use of some resources right next to it: the included Runfile is in a better position to be able to define where that is, than the primary Runfile is, in my opinion.

This can be split off to a separate issue, if preferred.

**Comment by TekWizely** [comment]
Howdy!  Let's start with a bit of devil's advocate:

The simplest (current) way to get the RUNFILE dir is likely:

_Runfile_
```
export RUNFILE=${.RUNFILE}

main:
   echo ${RUNFILE%/*}
```

A re-usable `RUNFILEDIR` can be achieved in two lines:

_Runfile_
```
export RUNFILE=${.RUNFILE}
export RUNFILEDIR=$(dirname ${RUNFILE})

main:
    echo $RUNFILEDIR
```

That said, I've actually also been grinding on `.RUNFILEDIR` attribute since the discussion of Sub-Module Support in #50

Honestly I use this value in the code constantly so its already handy, so its ease vs value ratio makes it a no-brainer ...

But wait, there's more ...

> it might also be convenient to have attributes for the paths relevant for the imported Runfile

Indeed I can see much value in included runfiles having easy access to their containing folder path.

But now we fall into one of (the two) hardest things: **Naming Things**

It _feels_ like we want to be able to capture the following:

* The primary runfile's Full Path
* The primary runfile's Containing Folder Path
* The current (included or primary) runfile's Full Path
* The current (included or primary) Containing Folder Path

It also _feels_ like we want to enable consistent usage of the variables, regardless if a runfile is primary or an included, ie.

We likely don't want the primary to have to use `.RUNFILE`, but includes having to use `.INCLUDEDRUNFILE` (or sumesuch) for the same concept.

Q: Could a runfile be a Primary runfile in one context, but an Included runfile in a different context?

If YES: Then the variables we create (and name) should represent the the same concept in both contexts.

If NO: Then an Include file **knows** its an include file, so we can have include-specific variables that are only valid in that context.

Q: Synonyms for _Primary_ ?

"Primary" is a big word, could we get by with a smaller word like:
* main
* root
* ???

Using "main" for discussion: We could introduce the following:

| Attribute | Description |
| --- | --- |
| `.RUNFILE` | Current runfile full path  (changes current behavior) |
| `.RUNFILE.DIR` | Current runfile directory |
| `.RUNFILE.MAIN` | Primary runfile full path. Matches `.RUNFILE` within primary file iteself |
| `.RUNFILE.MAIN.DIR` | Primary runfile directory. Matches `.RUNFILE.DIR` within primary file iteself |

Alternatively, we could invert them:

| Attribute | Description |
| --- | --- |
| `.RUNFILE` | Primary runfile full path  (current behavior) |
| `.RUNFILE.DIR` | Primary runfile directory |
| `.RUNFILE.CURRENT` | Current runfile full path. Matches `.RUNFILE` within primary file iteself |
| `.RUNFILE.CURRENT.DIR` | Current runfile directory. Matches `.RUNFILE.DIR` within primary file iteself |

Additionally, `CURRENT` could be replaced with something like `SELF`

| Attribute | Description |
| --- | --- |
| `.RUNFILE` | Primary runfile full path  (current behavior) |
| `.RUNFILE.DIR` | Primary runfile directory |
| `.RUNFILE.SELF` | Current runfile full path. Matches `.RUNFILE` within primary file iteself |
| `.RUNFILE.SELF.DIR` | Current runfile directory. Matches `.RUNFILE.DIR` within primary file iteself |

( although "self" feels more like programming and less like scripting )

Ok so if we used the first method, what would **you** use as the names for `"PRIMARY"` ?

And if we used the second method, what would you use as the names for `"CURRENT"`?

Thanks for starting the discussion !

-TW

**Comment by TekWizely** [comment]
@rburchell  me fears github emails are still routing to your /dev/null ?

**Comment by nikolay** [comment]
I think `root` is more meaningful than `primary` or `main`. Regarding `current` or `self`, it could also be `this` or `here`. Anyway, I prefer hierarchy to be `.SELF.RUNFILE...` as later on more attributes to `.SELF` could be added. Another option is to never have a prefix for the current one, i.e. `.RUNEFILE` to always be the current one and instead add `.ROOT.RUNFILE...` as it will be the least frequently used option... maybe.

**Comment by rburchell** [comment]
@TekWizely No, I got the notification, but simply didn't have enough time to respond at the moment, a lot going on in life. Good that it got solved, though.

**Comment by TekWizely** [comment]
> @TekWizely No, I got the notification, but simply didn't have enough time to respond at the moment, a lot going on in life. Good that it got solved, though.

LOL Thanks for the note, I was contemplating sending an email get proof of life :)

I hope you like the design decisions we made to for new attributes !
